@url = http://localhost:3000


### 1. Create report
#### Request
POST {{url}}/reports
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 1980,
  "mileage": 16000,
  "price": 20000,
  "lng": 0,
  "lat": 0
}

### 2. Get report
#### Request
GET {{url}}/reports/2

### 3. Update report
#### Request
PATCH {{url}}/reports/1/approve
Content-Type: application/json

{
  "approved": true
}

### 3. Get estimate
#### Request
GET {{url}}/reports/estimate?make=hyundai&model=i30&year=1984&lat=15&lng=15&mileage=10000

### 4. Delete report
#### Request
DELETE {{url}}/reports/1
